services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    container_name: diatonic-ai-prompts-prod
    ports:
      - "80:4000"
    volumes:
      - .:/srv/jekyll:ro  # Read-only for production
      - jekyll_bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=production
      - BUNDLE_PATH=/usr/local/bundle
    command: >
      bash -c "
        echo '🚀 PRODUCTION BUILD' &&
        echo '==================' &&
        echo '' &&
        echo 'Installing dependencies...' &&
        bundle install &&
        echo '' &&
        echo 'Building site for production...' &&
        bundle exec jekyll build &&
        echo '' &&
        echo 'Starting production server...' &&
        echo '' &&
        echo '📍 Production site available at:' &&
        echo '   http://localhost/diatonic-ai-prompts/' &&
        echo '' &&
        bundle exec jekyll serve 
          --host 0.0.0.0 
          --port 4000 
          --no-watch 
          --skip-initial-build
      "
    restart: unless-stopped

volumes:
  jekyll_bundle:
    driver: local
