services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    container_name: diatonic-ai-prompts-dev
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/srv/jekyll:cached
      - jekyll_bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    command: >
      bash -c "
        echo 'Installing Ruby dependencies...' &&
        bundle install &&
        echo '' &&
        echo '🚀 Starting Jekyll server on 0.0.0.0:4000...' &&
        echo '' &&
        echo '📍 Access URLs:' &&
        echo '   - Local:     http://localhost:4000/diatonic-ai-prompts/' &&
        echo '   - Network:   http://127.0.0.1:4000/diatonic-ai-prompts/' &&
        echo '' &&
        bundle exec jekyll serve --host=0.0.0.0 --port=4000 --livereload --livereload-port=35729 --incremental --force_polling --verbose
      "
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  jekyll_bundle:
    driver: local

networks:
  default:
    driver: bridge
